const {
    DB_CLIENT,
    DB_ACCESS_USER,
    DB_ACCESS_PASSWORD,
    DB_HOST,
    DB_PORT,
    DB_NAME,
    DB_CHANNEL_BINDING,
    DB_SSL_MODE,
    DB_SPRO_NAME,
    DB_SPRO_USER,
    DB_SPRO_PASS,
    DB_SPRO_HOST,
    DB_SPRO_PORT,
    DB_SPRO_SSL_CA,
    DB_SPRO_SSL_CERT,
    DB_SPRO_SSL_KEY,
} = process.env;

export const dbConfig = {
    client: DB_CLIENT,
    accessUser: DB_ACCESS_USER,
    accessPassword: DB_ACCESS_PASSWORD,
    host: DB_HOST,
    port: Number(DB_PORT),
    name: DB_NAME,
    channelBinding: DB_CHANNEL_BINDING,
    sslMode: DB_SSL_MODE,
    spro: {
        name: DB_SPRO_NAME,
        accessUser: DB_SPRO_USER,
        accessPassword: DB_SPRO_PASS,
        host: DB_SPRO_HOST,
        port: Number(DB_SPRO_PORT),
        sslCa: DB_SPRO_SSL_CA,
        sslCert: DB_SPRO_SSL_CERT,
        sslKey: DB_SPRO_SSL_KEY,
    },
};
